name: CI/CD react app

on:
    push: 
        branches: [main]
    workflow_dispatch: 

permissions: 
    contents: write

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 21
            
            - name: Install dependencies
              run: npm install
            
            - name: Build project
              run: npm run build

            - name: Debug Build Output
              run: ls -la

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: dist   # Ensure this matches the actual build output
